# nixpacks.toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

dependencies = [
    "pip",
    "wheel",
    "Red-DiscordBot"
]

[phases.build]
cmds = [
    "redbot-setup --no-prompt --instance-name mydiscordbot --backend json --data-path /var/lib/Red-DiscordBot/data",
]

[start]
cmd = "python3 -m redbot mydiscordbot --no-prompt --token $DISCORD_TOKEN -p $DISCORD_PREFIX $ADDITIONAL_LAUNCH_ARGS"

[variables]
DISCORD_TOKEN = "${{DISCORD_TOKEN}}"
DISCORD_PREFIX = "${{DISCORD_TOKEN}}"
ADDITIONAL_LAUNCH_ARGS = ""
